{
 "title": "Netatmo Weather Station",
 "tags": [ "influxdb" ],
 "time": { "from": "now/d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "Station",
    "query": "show tag values with key = \"station\""
   }
  ]
 },
 "panels": [
  {
   "title": "Temperatur",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "query": "SELECT last(value) FROM \"temperature\" WHERE (\"station\" =~ /^$Station$/) AND \"module\" =~ /^Aussentemperatur/ AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "station", "operator": "=~", "value": "/^$Station$/" },
      { "condition": "AND", "key": "module", "operator": "!=", "value": "Wohnzimmer" },
      { "condition": "AND", "key": "module", "operator": "!=", "value": "Technikraum" }
     ]
    }
   ]
  },
  {
   "title": "Luftfeuchtigkeit",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "humidity",
     "query": "SELECT last(value) FROM \"temperature\" WHERE (\"station\" =~ /^$Station$/) AND \"module\" =~ /^Aussentemperatur/ AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "station", "operator": "=~", "value": "/^$Station$/" },
      { "condition": "AND", "key": "module", "operator": "!=", "value": "Wohnzimmer" },
      { "condition": "AND", "key": "module", "operator": "!=", "value": "Technikraum" }
     ]
    }
   ]
  },
  {
   "title": "CO2",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "co2",
     "query": "SELECT last(value) FROM \"temperature\" WHERE (\"station\" =~ /^$Station$/) AND \"module\" =~ /^Aussentemperatur/ AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "station", "operator": "=~", "value": "/^$Station$/" },
      { "condition": "AND", "key": "module", "operator": "=", "value": "Wohnzimmer" }
     ]
    }
   ]
  },
  {
   "title": "Wind",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "windstrength",
     "query": "SELECT last(value) FROM \"temperature\" WHERE (\"station\" =~ /^$Station$/) AND \"module\" =~ /^Aussentemperatur/ AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "station", "operator": "=~", "value": "/^$Station$/" }
     ]
    }
   ]
  },
  {
   "title": "Regen (Tag)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "litre" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sum_rain_24",
     "query": "SELECT last(value) FROM \"temperature\" WHERE (\"station\" =~ /^$Station$/) AND \"module\" =~ /^Aussentemperatur/ AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "station", "operator": "=~", "value": "/^$Station$/" }
     ]
    }
   ]
  },
  {
   "title": "Altitude",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "altitude",
     "query": "SELECT last(\"value\") FROM \"altitude\" WHERE (\"station\" =~ /^$Station$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "station", "operator": "=~", "value": "/^$Station$/" }
     ]
    }
   ]
  },
  {
   "title": "Temperatur",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "$tag_station $tag_module",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "module" ], "type": "tag" },
      { "params": [ "station" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "query": "SELECT last(\"value\") FROM \"temperature\" WHERE (\"station\" =~ /^$Station$/) AND $timeFilter GROUP BY time(10m), \"module\", \"station\" fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "station", "operator": "=~", "value": "/^$Station$/" }
     ]
    }
   ]
  },
  {
   "title": "Luftfeuchtigkeit",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_station $tag_module",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "module" ], "type": "tag" },
      { "params": [ "station" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "humidity",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "station", "operator": "=~", "value": "/^$Station$/" }
     ]
    }
   ]
  },
  {
   "title": "CO2",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ppm" }
   ],
   "targets": [
    {
     "alias": "$tag_station $tag_module",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "module" ], "type": "tag" },
      { "params": [ "station" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "co2",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "station", "operator": "=~", "value": "/^$Station$/" }
     ]
    }
   ]
  },
  {
   "title": "Luftdruck",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "none", "label": "mbar" }
   ],
   "targets": [
    {
     "alias": "$tag_station $tag_module",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "module" ], "type": "tag" },
      { "params": [ "station" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "pressure",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "station", "operator": "=~", "value": "/^$Station$/" }
     ]
    }
   ]
  },
  {
   "title": "Windstärke",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "km/h" }
   ],
   "targets": [
    {
     "alias": "$tag_station $tag_module",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "module" ], "type": "tag" },
      { "params": [ "station" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "windstrength",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "station", "operator": "=~", "value": "/^$Station$/" }
     ]
    }
   ]
  },
  {
   "title": "Regen",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "l" }
   ],
   "targets": [
    {
     "alias": "$tag_station $tag_module",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "module" ], "type": "tag" },
      { "params": [ "station" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "sum_rain_1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "station", "operator": "=~", "value": "/^$Station$/" }
     ]
    }
   ]
  },
  {
   "title": "Lautstärke",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "dB" }
   ],
   "targets": [
    {
     "alias": "$tag_station $tag_module",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "module" ], "type": "tag" },
      { "params": [ "station" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "noise",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "station", "operator": "=~", "value": "/^$Station$/" }
     ]
    }
   ]
  },
  {
   "title": "Batterie",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_station $tag_module",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "module" ], "type": "tag" },
      { "params": [ "station" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "battery_percent",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "station", "operator": "=~", "value": "/^$Station$/" }
     ]
    }
   ]
  }
 ]
}